In [5]:
import numpy as np 

array = np.array([1,2,3,4])
print(array)
print(type(array))

[1 2 3 4]
<class 'numpy.ndarray'>


In [29]:
new = np.array(
    [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12],
     [13,14,15,16],]
)

print(new[2:,0:2])

[[ 9 10]
 [13 14]]


In [ ]:
# scaler arithmatic

In [ ]:
ar = np.array([1,2,3])

In [44]:
import numpy as np
rng = np.random.default_rng(seed=1) #random generation

ar = rng.integers(low=0,high=100,size=(3,3))
print(ar)

ne = np.where(ar <50 , 0 , ar) # filtering without flat
print(ne)

print(ar[ar % 2 == 0]) # flat filtering

[[47 51 75]
 [95  3 14]
 [82 94 24]]
[[ 0 51 75]
 [95  0  0]
 [82 94  0]]
[14 82 94 24]
