In [2]:
import numpy as np 

array = np.array([1,2,3,4])
print(array)
print(type(array))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
new = np.array(
    [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12],
     [13,14,15,16],]
)

print(new[2:,0:2])

[[ 9 10]
 [13 14]]


In [ ]:
# scaler arithmatic

In [4]:
ar = np.array([1,2,3])

In [5]:
import numpy as np
rng = np.random.default_rng(seed=1) #random generation

ar = rng.integers(low=0,high=100,size=(3,3))
print(ar)

ne = np.where(ar <50 , 0 , ar) # filtering without flat
print(ne)

print(ar[ar % 2 == 0]) # flat filtering

[[47 51 75]
 [95  3 14]
 [82 94 24]]
[[ 0 51 75]
 [95  0  0]
 [82 94  0]]
[14 82 94 24]


In [7]:
st = { 1, 2, 3 }

arr = np.array(list(st))
print(arr.dtype) 
arr = arr.astype(np.int16)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

int64
[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [12]:
# dictionary 

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()
# print(keys)
# print(values)
# print(items)

dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])


In [15]:
# keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [16]:
arr = np.array(list(items))
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


In [20]:
#np.empty
arr = np.full((4,3),2)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)


[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
<class 'numpy.ndarray'>
int64
(4, 3)
2
12


In [21]:
# np.random.rand(shape) 

arr = np.random.rand(2,3) # 0 ->1 

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[0.03013088 0.85585173 0.89328848]
 [0.50716184 0.0929499  0.0748663 ]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [30]:
arr = np.random.uniform(50,100, (3,3,4))   

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[[62.20793831 72.42505874 90.6929736  52.26841669]
  [86.5528439  58.10753133 68.7621988  82.60912569]
  [63.0570976  61.60189549 96.18625508 72.14926064]]

 [[65.19252373 99.33907306 56.07420207 57.46748711]
  [84.32502839 91.0188586  94.50772094 80.17218415]
  [79.49983564 53.1904521  83.6514892  94.94039316]]

 [[56.87976725 84.41584283 86.35651273 97.67812054]
  [54.80650857 73.4421931  56.98900706 90.3707346 ]
  [92.94283534 78.73691924 70.03050159 51.20442356]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


In [41]:
arr = np.arange(1 , 10 ,1)
mat = arr.reshape(3,3) 

print(arr) 
print(mat) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [85]:
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [87]:
lst = np.array([ 10 , 20 ,30 ,40 ]) 

values = lst[[0,3,1]]

print(values)


[10 40 20]


In [95]:
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])
# print(arr2)
print(arr2[[0,1] , [1,2]])

# # boolean kono kichu diye
# print(arr2[arr>1])
# arr2[arr2>2] = 0 

# print(arr2)

[2 6]


In [97]:
arr3  = np.array([[10,20,30] , [100,200,300] ] )

# iteration 
print(arr3)
for i in np.nditer(arr3):
    print(i)

[[ 10  20  30]
 [100 200 300]]
10
20
30
100
200
300
